version: "3"
services:
  usdrub-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: usdrub-bot:latest
    container_name: "usdrub-bot"
    restart: always
    ports:
      - "18001:18001"
    environment:
      - BOT_TOKEN=$${{ secrets.BOT_TOKEN }}
      - CRON_SPEC=* 9-20 * * *