name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
        - uses: actions/checkout@v3
        
        - name: Setup SSH key
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts

        - name: Create directory on remote host
          run: |
            ssh ${{ secrets.USER }}@${{ secrets.HOST }} "
            echo ${{ secrets.PASSWORD }} | sudo -S rm -r /usr/src/usdrub-bot
            echo ${{ secrets.PASSWORD }} | sudo -S mkdir -p /usr/src/usdrub-bot
            echo ${{ secrets.PASSWORD }} | sudo -S chmod 777 /usr/src/usdrub-bot"

        - name: Build image
          run: docker compose build
          
        - name: Save image
          run: |
            sudo docker save -o usdrub-bot.tar usdrub-bot:latest
            sudo chmod 777 usdrub-bot.tar

        - name: Copy files to remote host
          run: rsync -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" --archive --compress --delete docker-compose.yml usdrub-bot.tar ${{ secrets.USER }}@${{ secrets.HOST }}:/usr/src/usdrub-bot

        - name: Load and run docker container on remote host
          run: |
            ssh ${{ secrets.USER }}@${{ secrets.HOST }} "
            echo ${{ secrets.PASSWORD }} | sudo -S docker load -i /usr/src/usdrub-bot/usdrub-bot.tar
            echo ${{ secrets.PASSWORD }} | sudo -S docker compose run -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} -d usdrub-bot"
